# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: hello-world
    binary: hello-world
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w

archives:
  - id: default
    name_template: "hello-world_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - zip

checksum:
  name_template: checksums.txt

snapshot:
  version_template: "{{ incpatch .Version }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - '^chore'
