name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install devbox
        uses: bakito/devbox-install-action@712abf519829e31d6a78228f66a1dc722412ddf5 # v0.15.0
        with:
          enable-cache: 'true'

      - name: Run lint
        run: devbox run task lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install devbox
        uses: bakito/devbox-install-action@712abf519829e31d6a78228f66a1dc722412ddf5
        with:
          enable-cache: 'restore'

      - name: Run tests
        run: devbox run task test

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install devbox
        uses: bakito/devbox-install-action@712abf519829e31d6a78228f66a1dc722412ddf5
        with:
          enable-cache: 'restore'

      - name: Build action
        run: devbox run task snapshot

      - name: Build hello-world
        run: devbox run task build-hello-world

  test-action:
    name: Test Action
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Analyze Build Assets
        uses: ./
        with:
          release_name: v1.0.5
          vt_api_key: ${{secrets.VT_API_KEY}}
